name: blocapp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.2.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  path_provider: ^2.0.2
  hydrated_bloc: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true